### ISSUE TITLE
Release v0.3.0 checklist

### ISSUE THREAD

**Issue by sthenic** [sthenic/vls#4]
- [x] Specifying recursive include paths like `/path/to/some/dir/**` to search all the directories in `/path/to/some/dir` recursively.
- [x] Warn about unconnected/missing parameter assignments.
- [x] Add a few gifs to the README to demonstrate the main functions.
